# Generated by Django 5.0.6 on 2024-06-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about_info',
            field=models.TextField(default='author has not yet uploaded information'),
        ),
    ]
